### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.learn' has no attribute 'TensorFlowRNNRegressor'

### ISSUE THREAD

**Issue by dishang13** [marsbroshok/tensorflow-rnn-events-prediction#1]
The newer versions of tensorflow have removed TensorFlowRNNRegressor, TensorFlowRNNClassifier. Post the version of tensorflow used and upgrade the code to be compatible to recent releases.
Also in ValidationMonitor - n_classes and print_steps arguments have been removed.

**Comment by marsbroshok** [comment]
Hi, thanks for your feedback. I added note about TF version, but sadly I don't have time to update the notebook code. Still feel free to fork and update it if you wish.
